[build]

  command = "echo 'No build command needed for this example, just deploying functions and static site'" 
  
  publish = "." # <--- 將這一行從 "your_frontend_build_output_directory" 修改為 "."

  functions = "netlify/functions" 

[functions]
  directory = "netlify/functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  PYTHONPATH = "./netlify/functions"

